init:
  - git config --global core.autocrlf input

build_script:
  - build.cmd

deploy:
  - provider: NuGet
    api_key:
      secure: 7MS5+XWaFchMXFqzgneQCqo9U0DlxiPXe/KWWUnbCBDEizVn06EjdQZkWu1gbNOJ
    artifact: Package
    on:
      branch: master
      
nuget:
  project_feed: true
  
artifacts:
  - path: '*.nupkg'
    name: Package
